### ISSUE TITLE
Restify not working with nodejs v4.0.0 in mac os x

### ISSUE THREAD

**Issue by joaosousafranco** [restify/node-restify#897]
Hello,

i was trying my application that is using restify with nodejs v4.0.0, and it is not working. Once the require to restify is made the process just dies without giving any exception or error.

Thank you,
Joao Franco

**Comment by micahr** [comment]
@mrshogun can you provide an example script that exhibits the problem? Anything we can go off of to help assist you?

**Comment by pete-a** [comment]
I am also experiencing this, restify will not install. Looks to be an issue with DTrace 0.5:
OS X 10.10.5
Node v4.0.0

**Installing restify**

    $ npm install restify --save
    > dtrace-provider@0.5.0 install     
    /Users/.../node_modules/restify/node_modules/dtrace-provider
    > node scripts/install.js
   
    ---------------
    Building dtrace-provider failed with exit code 1 and signal 0
    re-run install with environment variable V set to see the build output
    ---------------
    ...

**Basic script**

    /* index.js */
    var restify = require('restify')
    var server = restify.createServer()
    server.get('/hello_wold', (request, response, next) => {
      response.send('Hello World')
      next() 
    }) 
    server.listen(8080)

**Output**

    $ node index.js 
    { [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
    { [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
    { [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }

**Comment by micahr** [comment]
Dtrace 0.5 won't work with Node 4. It was just released today, and we haven't had a chance to validate what is necessary to get it working with Restify.

**Comment by thomashilzendegen** [comment]
dtrace 0.6 has node v4 support, maybe updating is enough?

**Comment by thomashilzendegen** [comment]
@mrshogun just run in the node_modules/restify directory the following to test if 0.6 is a possible fix:

npm i dtrace-provider@0.6.0

**Comment by KenanSulayman** [comment]
@thomashilzendegen It is indeed a fix.

**Comment by mrshogun** [comment]
Ill try that asap, in the mean time do you have an ETA for the fix in restify? Im using the latest version and i dont have any problem with updating, so once you will release a fix ill update on my side.

Thank you

**Comment by micahr** [comment]
4.0.1 is out, upgrade and let us know if that fixes your issue.

**Comment by micahr** [comment]
@mrshogun - What fix in restify?

**Comment by pete-a** [comment]
4.0.1 now installs successfully with Node 4.0.0 for me :+1:

**Comment by lvegerano** [comment]
This issue still happening. I'm using restify v4.0.3 using either node 0.10.40 or 4.2.2.

```
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
```

**Comment by cprwhite** [comment]
I'm have this problem too using testify v4.0.3 and node 4.2.3
```
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
```

**Comment by willkramer** [comment]
@cprwhite @lvegerano have you tried uninstalling the restify module and re-installing it?

I had the same error this morning after upgrading to node v4.2.3 on my Mac and running a npm update doesn't seem to fix the issue.

The commands I ran were:

`npm uninstall restify`
`npm install restify`

**Comment by lvegerano** [comment]
@willkramer I did not spend much time on it. I was on a mission to create a microservice so I just switched to using [HapiJS](http://hapijs.com/). Also there is memory leak noted in the issues with some of the middleware that also pushed me away.

**Comment by micahr** [comment]
@lvegerano - Do you mind pointing me towards the issues with memory leaks?

It makes sense that after upgrading Node you'd have to uninstall and reinstall a module with a dependency on a native module (Bunyan / dtrace-provider) as it needs to be recompiled with the newer version of node-gyp.

**Comment by lvegerano** [comment]
@micahr I did not find this leak. I was making reference to https://github.com/restify/node-restify/issues/431 While it may not be an issue the inconclusiveness of the issue deterred me from using restify.

**Comment by DonutEspresso** [comment]
The error is from bunyan, and is non-fatal. You may want to check out this [thread](https://github.com/trentm/node-bunyan/issues/216) for some of the proposed solutions.

**Comment by markmcdermid** [comment]
I came across this issue too but a simple reinstall fixed it

**Comment by u84six** [comment]
This seems to be happening again with Restify 6.3.2 and Node 9.0.0. If this because you haven't had a chance to update?

**Comment by retrohacker** [comment]
Hey @u84six,

Thanks for letting us know. Is this specifically DTrace?

**Comment by u84six** [comment]
Yes, specifically DTrace. I confirmed it was restify installation by uninstalling, deleting node_modules dir and then running npm install. No problem without restify.

**Comment by retrohacker** [comment]
DTrace uses native bindings, it must not be updated for Node v9. Not sure what work goes into that. Marking this as help wanted for now.

Worst case scenario we could pull out dtrace, I'm not sure how much it is used (queue incoming flood of use cases)

**Comment by u84six** [comment]
While searching for the solution to this problem, I got many hits with problems related to DTrace. Probably a good idea to get rid of it.
